# Generated by Django 4.2.23 on 2025-08-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_fileupload_user_paymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='gateway_response',
            field=models.JSONField(null=True),
        ),
    ]
