# Generated by Django 4.2.23 on 2025-08-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_paymenttransaction_gateway_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='can_upload_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='complete_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
