# Generated by Django 4.2.23 on 2025-08-10 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_paymenttransaction_can_upload_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='complete_at',
            new_name='completed_at',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
