# Generated by Django 4.2.23 on 2025-08-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_rename_complete_at_paymenttransaction_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='upload_time',
            field=models.DateTimeField(null=True),
        ),
    ]
